# Generated by Django 4.0 on 2025-02-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('price_booking', models.FloatField(blank=True, null=True)),
                ('price_agoda', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('booking_url', models.URLField(blank=True, null=True)),
                ('agoda_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
